---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ngci-virtual-service
  namespace: ngci
spec:
  hosts:
  - "ngci.localdomain"
  gateways:
  - ngci-gateway
  http:
  - match:
    - uri:
        exact: /data
    route:
    - destination:
        host: vrealize-controller-service
        port:
          number: 8080